Models/ErrorViewModel.cs
namespace Assignment5.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Person.cs
namespace Assignment5;
public class Person
    {
        public string? FirstName { get; set; }
        public string? LastName { get; set; }

        public string? Gender { get; set; }

        public DateTime DOB { get; set; }

        public string? PhoneNumber { get; set; }

        public string? BirthPlace { get; set; }

        public int Age
        {
            get
            {
                return DateTime.Now.Year - DOB.Year;
            }
        }

        public bool IsGraduated { get; set; }


        public int TotalDays{
            get{
                return (int)(DateTime.Now - DOB).TotalDays;
            }
        }
        // public int CompareTo(object? obj){
        //     return TotalDays.CompareTo(((Member)obj).TotalDays);
        // }
        public string FullName { get{
            return $"{LastName} {FirstName}";
        } }
    }

Controllers/AssigmentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Assignment5;
using CsvHelper;
using System.Globalization;
using CsvHelper.TypeConversion;

namespace Assignment5.Controllers;

public class AssignmentController : Controller
{
    static List<Person> persons = new List<Person>
        {
            new Person
            {
                FirstName = "Phuong",
                LastName = "Nguyen Nam",
                Gender = "Male",
                DOB = new DateTime(2001, 1, 22),
                PhoneNumber = "",
                BirthPlace = "Phu Tho",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Nam",
                LastName = "Nguyen Thanh",
                Gender = "Male",
                DOB = new DateTime(2001, 1, 20),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Son",
                LastName = "Do Hong",
                Gender = "Male",
                DOB = new DateTime(2000, 11, 6),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Huy",
                LastName = "Nguyen Duc",
                Gender = "Male",
                DOB = new DateTime(1996, 1, 26),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Hoang",
                LastName = "Phuong Viet",
                Gender = "Male",
                DOB = new DateTime(1999, 2, 5),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Long",
                LastName = "Lai Quoc",
                Gender = "Male",
                DOB = new DateTime(1997, 5, 30),
                PhoneNumber = "",
                BirthPlace = "Bac Giang",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Thanh",
                LastName = "Tran Chi",
                Gender = "Male",
                DOB = new DateTime(2000, 9, 18),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            },
            new Person
            {
                FirstName = "Person",
                LastName = "Old",
                Gender = "Male",
                DOB = new DateTime(1996, 1, 14),
                PhoneNumber = "",
                BirthPlace = "Ha Noi",
                IsGraduated = false
            }
        };

    // [Route("Assignment/Malemembers")]
    // [Route("Assignment/male-members")]
    //[Route("Nashtech/Assignment/malemembers")]
    public IActionResult GetMembers(){
        var result = from person in persons select person;
        return new ObjectResult(result);
    }
    public IActionResult GetMalesMember()
    {
        var result = persons.Where(m => m.Gender.Equals("Male", StringComparison.CurrentCultureIgnoreCase)).ToList();
        return new ObjectResult(result);
        //return Json(result);

    }
    // [Route("Assignment/oldest-members")]
    // [Route("Nashtech/Assignment/oldest-members")]
    public IActionResult GetOldestMemberbyAge()
    {
        var MaxAge = persons.Max(m => m.Age);
        var oldest = persons.First(m => m.Age == MaxAge);
        return new ObjectResult(oldest);
        //using OrderBy
        //return members.OrderByDescending(m=>m.Age).First();
        //return members.OrderBy(m=>m.Age).Last();

        //using LinQ Query
        // var OldList = from member in members
        //               orderby member.Age descending
        //               select member;
        // return OldList.First();
    }
    //[Route("Assignment/fullname")]
    //[Route("Nashtech/Assignment/fullname")]
    public IActionResult GetFullName()
    {
        var result = persons.Select(m => m.FullName);
        return Json(result);
    }
    //[Route("Assignment/split-member-by-birth-year")]
    //[Route("Nastech/Assignment/split-member-by-birth-year")]
    public IActionResult SplitMemberbyBirthYear(int year)
    {
        var result = from person in persons
                     group person by person.DOB.Year.CompareTo(year) into grp
                     select new
                     {
                         Key = grp.Key switch
                         {
                             -1 => $"Birth Year less than {year}",
                             0 => $"Birth Year equals to {year}",
                             1 => $"Birth Year greater than {year}",
                             _ => string.Empty
                         },
                         Data = grp.ToList()
                     };

        return Json(result);
    }
    //[Route("Assignment/exportfile")]
    // [Route("Nastech/Assignment/exportfile")]
    public IActionResult ExportFile()
    {
        var result = WriteCsvToMemory(persons);
        var memoryStream = new MemoryStream(result);
        return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = "person.csv" };
    }
    public byte[] WriteCsvToMemory(List<Person> records)
    {
        using (var stream = new MemoryStream())
        using (var writer = new StreamWriter(stream))
        using (var csvWriter = new CsvWriter(writer, CultureInfo.InvariantCulture))
        {

            var options = new TypeConverterOptions { Formats = new[] { "dd/MM/yyyy" } };
            csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime>(options);

            csvWriter.WriteRecords(records);
            writer.Flush();
            return stream.ToArray();
        }
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Assignment5.Models;

namespace Assignment5.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult GetFullName(){
        return View();
    }
    public IActionResult SplitMemberbyBirthYear(){
        return View();
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/MemberList.cshtml
@{
    ViewData["Title"] = "Member List";
}

<div class="text-center">
    <h1 class="display-4">Member</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="GetFullName">FullName List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Assignment5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>